name: MLOps CI/CD Pipeline (California-Housing-Price_Prediction)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Lint code
        run: |
          source venv/bin/activate
          pip install flake8
          flake8 --config .flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pip install pytest
          pytest -s ./tests/

  docker_build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Docker
          run: |
            sudo apt-get update
            sudo apt-get install -y docker.io

            - name: Install Docker Compose
              run: |
                sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set Docker Hub username in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set Docker Hub password in GitHub Secrets

      - name: Verify Docker and Docker Compose versions
        run: |
          docker --version
          docker-compose --version

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Push Docker images to Docker Hub
        run: |
          docker-compose -f docker-compose.yml push
