global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    metrics_path: /app/api/v1/housing-price/metrics
    static_configs:
      - targets: ['app:5001']